title: Mohanraj Chinnapaiyan
logo: /github_portfolio_pic.jpeg
description: AI/ML Evangelist
#description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

